version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    # command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    command: celery -A app.celery.app worker --loglevel=debug
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0
    depends_on:
      - app
      - redis

  redis:
    image: redis:7
    ports:
      - 6380:6379

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --broker=redis://redis:6380/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0
    depends_on:
      - app
      - redis
      - worker

volumes:
  dev-db-data:
  dev-static-data: